 library(MASS)
library(dplyr)      # dataframe management
library(tidyr)      # dataframe management
library(abind)      # dataframe management
library(tidyverse)   
select <- dplyr::select
source("./CF_functions.R")


  calculate.slost <- function(Total_RemainingNatural_areas, Land_use_areas, CI, ratio_eco, vulnerability) { 
    # Total_RemainingNatural_areas : dataframe with two columns, one with the total original areas, one with the remaining natural areas. The rows correspond to the 
      # ecoregions and are sorted in alphabetical order according to the ecoregion codes (AA0101, AA0102, etc.)
    # Land_use_areas : dataframe which contains one column per each land use category. The rows correspond to the 
      # ecoregions and are sorted in alphabetical order according to the ecoregion codes (AA0101, AA0102, etc.)
    # CI can be TRUE or FALSE. TRUE = the CI will be calculated, FALSE = the CI will not be calculated
    # ratio_eco: 4dimension array with the response ratios
    # vulnerability: "ON" or "OFF" 
    
    if (CI == FALSE) {distribution = "OFF"
                    sumulations = 2} else if(CI == TRUE){distribution = "Weibull"
                                                          simulations = 1000}
    if((CI != FALSE & CI != TRUE) | missing(CI)) {stop("Select one option for the calculation of the confidence intervals (FALSE or TRUE)")}
    
    
    ############################# CALCULATION OF THE INPUT PARAMETERS ############################# 
    
    
    # The parameters are calculated using the functions in the file parameters_calculation.R
    
      # ratio_eco = calculate.RR(distribution, cutoff)        # four dimension array containing the response ratio per ecoregion (1st dimensio), land use category (2nd dimension) and taxa (3rd dimension).
      # The fourth dimension contains either two equal values corresponding to the median of the raw response ratios or the n simulations generated by teh given distribution
      
      weight_tx = prepare.Sorg.VS.weighting(vulnerability = vulnerability)[["Weights"]]    # dataframe containing the weighting factors (rows: ecoregions, columns: weights per taxonomic group)
      Sorg_VS = prepare.Sorg.VS.weighting(vulnerability = vulnerability)[["Sorg_VS"]]      #
      zvalues = prepare.zvalues(distribution)
      
      necoregions = dim(ratio_eco)[1]                       # number of ecoregions = length of the first dimension of the array ratio_eco 
      simulations = dim(ratio_eco)[4]                       # number of simulations = length of the fourth dimension of the array ratio_eco
      Ecoregions = dimnames(ratio_eco)[[1]]
      Ecoregions = data.frame(Ecoregions)
      names(Ecoregions) ="Eco_code"
    
        
    ############################# CALCULATION OF THE IMPACTS ############################# 
      
      # specieslost_sim calculates the affinity (h), the suitable areas (sum(hi*Ai)) and the species lost (no allocation, no weighting, 
      # no aggregation, as in eq. 11.3 of LCImpact method for land stress (Chaudhary, 2016), but multiplied also by the vulnerability scores)
        system.time(  
        Slost_h_a_suit <- specieslost_sim(Sorg_VS, Total_RemainingNatural_areas$A_org, Total_RemainingNatural_areas$A_new, Land_use_areas, zvalues, ratio_eco, simulations)
        )
        
        h = Slost_h_a_suit[[1]]       # list of 3d array. The lenght of the list is equal to the number of simulations. Each array contains the affinity values per ecoregion (1st dim), land use category (2nd dim) and per taxon (3rd dim) 
                                      # Ecoregions are in alphabetical order according to the ecoregion code, AA0101, AA0102, etc. Taxa are "Plants"  "Birds"   "Mammals".
                                      # If CI are not calculated and number of simulations = 2, the list contains only two equal dataframes.
        taxa <- unlist(dimnames(h[[1]])[3])   # taxa considered
        
        Slost = Slost_h_a_suit[[3]]   # A single dataframe containing the impacts per taxonomin group (columns) and per ecoregion (rows, in alphabetical order according to the ecoregion code, AA0101, AA0102, etc).
                                      # The number of columns is the number of taxonomic groups multiplied by the number of simulations
        
      # allocation_sim calculates the allocation factors used to allocate the impacts to the land use categories
        a_factor <- allocation_sim(h, Land_use_areas, simulations)    # list of 3d array. The lenght of the list is equal to the number of simulations. Each array contains the allocation values per ecoregion (1st dim), land use category (2nd dim) and per taxon (3rd dim) 
                                                                      # Ecoregions are in alphabetical order according to the ecoregion code, AA0101, AA0102, etc. Taxa are "Plants"  "Birds"   "Mammals".
        
      # remove what is not needed anymore
        rm(h, Land_use_areas, Total_RemainingNatural_areas, Slost_h_a_suit)      
      
      # prepare the structure of the arrays which have to be filled out with the results of the calculation
        Slost_lf <- array(NA, dim = c(dim(a_factor[[1]]), simulations), dimnames = list(dimnames(a_factor[[1]])[[1]],dimnames(a_factor[[1]])[[2]],dimnames(a_factor[[1]])[[3]], 1:simulations))
        Slost_tx_w <- Slost
        
      # test_weight <- apply(Slost, MARGIN = 3, function(x) x*weight_tx)
      # multiply Slost by the allocation factor and the weights
        ptm <- proc.time()
        
        for (n in 1:simulations) {
          
          Slost_tx_w[,,n] <- Slost[,,n]*weight_tx[,]
          
          for (i in 1:dim(a_factor[[n]])[2]) {
            
            Slost_lf[,i,,n] <- Slost_tx_w[,,n]*a_factor[[n]][,i,]
            
          }
        }
        proc.time() - ptm      
      
        
        
      # Results per taxa 
        
        Slost_taxa_df <- list()       # list to be filled out with the results per taxa (each element of the list will be a dataframe with the impacts per ecoregion and land use category)
        Slost_taxa_matrix <- list()   # list to be filled out with the results per taxa (each element of the list will be a matrix with the impacts per ecoregion and land use category)
        Slost_df <- apply(Slost_lf, c(1,2,3), median)                           # compute the median of the impacts
        Slost_df <- data.frame(Slost_df)                                            # convert the matrix to a dataframe
        
        for (i in 1:length(taxa)) {

          temp <- Slost_df %>% select(contains(toString(taxa[i])))                          # select the columns for taxon i
          Slost_taxa_matrix[[taxa[i]]] <- data.matrix(temp)                                 # fill out the matrix
          rownames(Slost_taxa_matrix[[taxa[i]]]) <- rownames(temp)                          # give names to the rows of the matrix
          Slost_taxa_df[[taxa[i]]] <- temp %>%                                              # save it in the list
                          add_column(Ecoregions, .before = names(temp)[1])                  # create a column with the codes of the ecoregions
            } 
          
        rm(temp, Slost_df)
        
        # sum the impacts   
          system.time(
            Slost_aggr <- apply(Slost_lf, MARGIN = c(1,2,4), sum, na.rm = TRUE)
            )
      
        Slost_aggr_sort <- Slost_aggr
        
        ptm <- proc.time()
        for(i in 1:necoregions) {
          for (j in 1:dim(Slost_aggr)[2]) {
            if ((length(which(is.na(Slost_aggr[i,j,])))) == 0) {
              Slost_aggr_sort[i,j,] <- sort(Slost_aggr[i,j,])
            } #else {Slost_aggr_sort[i,j,] = Slost_aggr[i,j,]}
          }
        }
        proc.time() - ptm      
      
      
        if (distribution == "OFF") {
          Slost_aggr_2.5 <- 0
          Slost_aggr_97.5 <- 0
        } else {
          Slost_aggr_2.5 <- Slost_aggr_sort[,,round(0.025*simulations)]
          Slost_aggr_97.5 <- Slost_aggr_sort[,,(simulations - round(0.025*simulations))]
        }
        
        
        Slost_aggr_median <- apply(Slost_aggr, c(1,2), median)
        
        Slost_aggr_df <- data.frame(Slost_aggr_median) %>%
                      add_column(Ecoregions, .before = names(Slost_aggr_median)[1])
        
        result = list("Aggr_matrix"= Slost_aggr_median, "Aggr_df"= Slost_aggr_df, "PerTaxon_matrix"= Slost_taxa_matrix, "Pertaxon_df"= Slost_taxa_df,
                        "Aggr2.5_matrix"= Slost_aggr_2.5, "Aggr97.5_matrix"= Slost_aggr_97.5)
        
          
          return(result)
        
      }
  
  
